version: '3'

services:
  api:
    container_name: rest-api
    image: rest-api:latest
    networks:
      - local
    ports:
      - 8081:8081
    env_file:
      - .env
    environment:
      - "HTTP_HOST_ADDRESS=0.0.0.0:8081"

  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    networks:
      - local
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=placement3_service_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  local: