version: '3'

services:
  api:
    container_name: template-api
    image: template-api:latest
    ports:
      - 8081:8081
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./local_env/local.env
    environment:
      - "HTTP_HOST_ADDRESS=0.0.0.0:8081"

  mysql:
    container_name: mysql
    image: mysql:8.0.36
    restart: always
    volumes:
      - ./local_env/db/:/docker-entrypoint-initdb.d/
    env_file:
      - ./local_env/local.env
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-pSuperS3cur3" ]
      interval: 10s
      timeout: 3s
      retries: 10
