basePath: /api/v1
definitions:
  apperr.StatusError:
    properties:
      client_msg:
        description: sometimes we do not want to expose to the client some error details
        type: string
      err: {}
      status:
        type: integer
    type: object
  model.User:
    properties:
      id:
        type: integer
      lastname:
        type: string
      name:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: This is a template api for a service with DB
  title: Template Api
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      parameters:
      - description: User payload
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperr.StatusError'
        "500":
          description: Internal Server Error
          schema: {}
      tags:
      - AddUser
  /users/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperr.StatusError'
        "500":
          description: Internal Server Error
          schema: {}
      tags:
      - UserGetId
swagger: "2.0"
